<?php

namespace AppBundle\Repository;

/**
 * ProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
