<?php

namespace AppBundle\Repository;

/**
 * WordProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
